fixed in prod_ios too

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -533,6 +533,15 @@ jobs:
       - run: node --version
       - attach_workspace: &attach_workspace
           at: /tmp/workspace
+      - run:
+          name: Install AWS CLI
+          command: |
+            if ! command -v aws &> /dev/null; then
+              echo "AWS CLI not found, installing..."
+              brew install awscli
+            else
+              echo "AWS CLI is already installed."
+            fi            
       - aws-cli/setup:
           profile-name: WEB IDENTITY PROFILE
           role-arn: '$OIDC_CIRCLE_CI_ROLE_ARN'
